<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Hase.DesktopHost.App.Lab</RootNamespace>
    <StartupObject>Hase.DesktopHost.App.Lab.LabApp</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hase.DesktopHost.App\Hase.DesktopHost.App.csproj" />
    <ProjectReference Include="..\Hase.Scpi.Kel103.DesktopHost\Hase.Scpi.Kel103.DesktopHost.csproj" />
    <ProjectReference Include="..\Hase.Mcnf.RfLab.DesktopHost\Hase.Mcnf.RfLab.DesktopHost.csproj" />
  </ItemGroup>

</Project>
