[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$RollbackDirectory)
$ErrorActionPreference="Stop";Set-StrictMode -Version Latest
function WriteJson($path,$value){$u=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllText($path,($value|ConvertTo-Json -Depth 10),$u)}
try{
 if($env:OS-ne"Windows_NT"){throw"platform"};$rollback=[IO.Path]::GetFullPath($RollbackDirectory);$planPath=Join-Path $rollback "transaction-plan.json";if(-not(Test-Path $planPath -PathType Leaf)){throw"plan"};$plan=Get-Content $planPath -Raw|ConvertFrom-Json;if($plan.schemaVersion-ne1-or$plan.purpose-cne"hase-minipc-python-provisioning-transaction"){throw"plan"}
 $tool=Split-Path -Parent $MyInvocation.MyCommand.Path;$pkg=Split-Path -Parent $tool;$repo=[IO.Path]::GetFullPath((Split-Path -Parent(Split-Path -Parent $pkg)));if(@(&git -C $repo status --porcelain).Count-ne0){throw"repository"};$head=(&git -C $repo rev-parse HEAD).Trim();$origin=(&git -C $repo rev-parse origin/main).Trim();if($head-ne$origin){throw"repository"};&git -C $repo merge-base --is-ancestor ([string]$plan.repositoryHead) $head;if($LASTEXITCODE-ne0){throw"repository"}
 if(@(Get-Process Hase.DesktopHost.App,Hase.Client.Wpf.App -ErrorAction SilentlyContinue).Count-ne0){throw"processes"}
 $entries=@($plan.entries);foreach($entry in $entries){if($entry.existed){if(-not(Test-Path $entry.path -PathType Leaf)-or(Get-FileHash $entry.path -Algorithm SHA256).Hash.ToLowerInvariant()-cne[string]$entry.sha256){throw"revision"}}elseif(Test-Path $entry.path){throw"target"}}
 $root=[string]($entries|? name -eq "provisioningDirectory").path;$cert=[string]($entries|? name -eq "certificate").path;$key=[string]($entries|? name -eq "privateKey").path;$profile=[string]($entries|? name -eq "pythonProfile").path;$enrollment=[string]($entries|? name -eq "enrollment").path;$policy=[string]($entries|? name -eq "authorizationPolicy").path;$app=[string]($entries|? name -eq "applicationProfile").path
 $policyCandidate=Join-Path $rollback "authorization-policy.candidate.json";$appCandidate=Join-Path $rollback "application-profile.candidate.json";foreach($f in @($policyCandidate,$appCandidate,[string]$plan.sourceProfilePath)){if(-not(Test-Path $f -PathType Leaf)){throw"candidate"}}
 $journal=Join-Path $rollback "publication-journal.json";if(Test-Path $journal){throw"recovery-required"};$state=[ordered]@{schemaVersion=1;purpose="hase-minipc-python-publication";status="created";entries=$entries};WriteJson $journal $state
 [IO.Directory]::CreateDirectory($root)|Out-Null;$owner=[Security.Principal.WindowsIdentity]::GetCurrent().User;$acl=[Security.AccessControl.DirectorySecurity]::new();$acl.SetOwner($owner);$acl.SetAccessRuleProtection($true,$false);$acl.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($owner,"FullControl","ContainerInherit,ObjectInherit","None","Allow"));Set-Acl $root $acl
 Copy-Item $policyCandidate $policy;$state.status="initial-policy-published";WriteJson $journal $state
 $policyHash=(Get-FileHash $policy -Algorithm SHA256).Hash.ToLowerInvariant();$operator=Join-Path $repo "src\Hase.Python.CredentialProvisioning.Operator";$operatorArguments=@("provision","--signing-root-thumbprint",[string]$plan.signingRootThumbprint,"--trust-policy-id",[string]$plan.trustPolicyId,"--source-profile",[string]$plan.sourceProfilePath,"--provisioning-directory",$root,"--certificate",$cert,"--private-key",$key,"--profile",$profile,"--enrollment",$enrollment,"--authorization-policy",$policy,"--expected-authorization-policy-sha256",$policyHash,"--validity-days",[string]$plan.validityDays)
 &dotnet run --project $operator -c Release -- @operatorArguments 1>$null 2>$null 3>$null 4>$null 5>$null 6>$null;if($LASTEXITCODE-ne0){throw"credential-publication"};$state.status="credential-published";WriteJson $journal $state
 $stage=$app+".stage-"+[guid]::NewGuid().ToString("N");Copy-Item $appCandidate $stage;Set-Acl $stage (Get-Acl $app);[IO.File]::Replace($stage,$app,$null);$state.status="committed";WriteJson $journal $state;Remove-Item $journal -Force
 Write-Host "Prepared plan revalidated       : True";Write-Host "Private custody created         : True";Write-Host "Python credential published     : True";Write-Host "Enrollment published            : True";Write-Host "Authorization policy published  : True";Write-Host "Application profile published   : True";Write-Host "Existing Client access preserved: True";Write-Host "Durable transaction committed   : True";Write-Host "Runtime Host remained stopped   : True";Write-Host "MiniPC Python publication ready : True"
}catch{Write-Error "MiniPC Python credential publication failed; explicit recovery may be required.";exit 1}
