import hase


def test_package_exposes_the_approved_profile_surface() -> None:
    assert hase.__version__ == "0.1.0"
    assert hase.__all__ == [
        "BooleanDataDescriptor",
        "ByteArrayDataDescriptor",
        "CommandArgumentDescriptor",
        "CommandDescriptor",
        "DataDescriptor",
        "EndpointConnectionState",
        "EndpointConnectionStatus",
        "EndpointDescriptor",
        "EventDescriptor",
        "EventPayloadDescriptor",
        "InstrumentDescriptor",
        "NumericDataDescriptor",
        "ProfileValidationError",
        "PropertyOperationResult",
        "PropertyOperationStatus",
        "PropertyProjectionError",
        "PropertyQuality",
        "PropertyScalar",
        "PropertyTarget",
        "PropertyValue",
        "PropertyAccessMode",
        "PropertyDescriptor",
        "Quantity",
        "RuntimeEndpointSnapshot",
        "RuntimeHostClient",
        "RuntimeHostClientError",
        "RuntimeHostChannel",
        "RuntimeHostChannelError",
        "RuntimeHostApiVersion",
        "RuntimeHostProfile",
        "RuntimeHostSnapshot",
        "SnapshotProjectionError",
        "StringDataDescriptor",
        "Unit",
        "ValueRange",
        "__version__",
        "load_runtime_host_profile",
        "open_runtime_host_channel",
        "project_property_operation_result",
        "project_property_target",
        "project_runtime_host_snapshot",
    ]
