<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hase.Core\Hase.Core.csproj" />
    <ProjectReference Include="..\Hase.DesktopHost\Hase.DesktopHost.csproj" />
    <ProjectReference Include="..\Hase.Runtime\Hase.Runtime.csproj" />
    <ProjectReference Include="..\Hase.Runtime.Transport\Hase.Runtime.Transport.csproj" />
    <ProjectReference Include="..\Hase.Scpi.Kel103\Hase.Scpi.Kel103.csproj" />
    <ProjectReference Include="..\Hase.Scpi.Kel103.Hosting\Hase.Scpi.Kel103.Hosting.csproj" />
    <ProjectReference Include="..\Hase.Transport\Hase.Transport.csproj" />
  </ItemGroup>

</Project>
