<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="Prism.DryIoc" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Media\Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Media\Assets\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hase.Client.Grpc\Hase.Client.Grpc.csproj" />
    <ProjectReference Include="..\Hase.Client.Wpf\Hase.Client.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
