# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hase._generated import runtime_host_remote_api_v1_pb2 as hase_dot___generated_dot_runtime__host__remote__api__v1__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hase/_generated/runtime_host_remote_api_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeHostRemoteApiStub:
    """Version 1 remote contract for operational runtime-host access.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSnapshot = channel.unary_unary(
                '/hase.runtime.remote.v1.RuntimeHostRemoteApi/GetSnapshot',
                request_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.GetSnapshotRequest.SerializeToString,
                response_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.GetSnapshotResponse.FromString,
                _registered_method=True)
        self.ReadCachedProperty = channel.unary_unary(
                '/hase.runtime.remote.v1.RuntimeHostRemoteApi/ReadCachedProperty',
                request_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ReadCachedPropertyRequest.SerializeToString,
                response_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.CachedPropertyResult.FromString,
                _registered_method=True)
        self.ReadAuthoritativeProperty = channel.unary_unary(
                '/hase.runtime.remote.v1.RuntimeHostRemoteApi/ReadAuthoritativeProperty',
                request_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ReadAuthoritativePropertyRequest.SerializeToString,
                response_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.PropertyOperationResult.FromString,
                _registered_method=True)
        self.WriteProperty = channel.unary_unary(
                '/hase.runtime.remote.v1.RuntimeHostRemoteApi/WriteProperty',
                request_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.WritePropertyRequest.SerializeToString,
                response_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.PropertyOperationResult.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/hase.runtime.remote.v1.RuntimeHostRemoteApi/ExecuteCommand',
                request_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.CommandOperationResult.FromString,
                _registered_method=True)
        self.Observe = channel.unary_stream(
                '/hase.runtime.remote.v1.RuntimeHostRemoteApi/Observe',
                request_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveRequest.SerializeToString,
                response_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveResponse.FromString,
                _registered_method=True)
        self.ObserveDiagnostics = channel.unary_stream(
                '/hase.runtime.remote.v1.RuntimeHostRemoteApi/ObserveDiagnostics',
                request_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveDiagnosticsRequest.SerializeToString,
                response_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ProjectedDiagnosticObservation.FromString,
                _registered_method=True)


class RuntimeHostRemoteApiServicer:
    """Version 1 remote contract for operational runtime-host access.
    """

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCachedProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAuthoritativeProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObserveDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeHostRemoteApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.GetSnapshotRequest.FromString,
                    response_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.GetSnapshotResponse.SerializeToString,
            ),
            'ReadCachedProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCachedProperty,
                    request_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ReadCachedPropertyRequest.FromString,
                    response_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.CachedPropertyResult.SerializeToString,
            ),
            'ReadAuthoritativeProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadAuthoritativeProperty,
                    request_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ReadAuthoritativePropertyRequest.FromString,
                    response_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.PropertyOperationResult.SerializeToString,
            ),
            'WriteProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteProperty,
                    request_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.WritePropertyRequest.FromString,
                    response_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.PropertyOperationResult.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.CommandOperationResult.SerializeToString,
            ),
            'Observe': grpc.unary_stream_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveRequest.FromString,
                    response_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveResponse.SerializeToString,
            ),
            'ObserveDiagnostics': grpc.unary_stream_rpc_method_handler(
                    servicer.ObserveDiagnostics,
                    request_deserializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveDiagnosticsRequest.FromString,
                    response_serializer=hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ProjectedDiagnosticObservation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hase.runtime.remote.v1.RuntimeHostRemoteApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hase.runtime.remote.v1.RuntimeHostRemoteApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeHostRemoteApi:
    """Version 1 remote contract for operational runtime-host access.
    """

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hase.runtime.remote.v1.RuntimeHostRemoteApi/GetSnapshot',
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.GetSnapshotRequest.SerializeToString,
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.GetSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadCachedProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hase.runtime.remote.v1.RuntimeHostRemoteApi/ReadCachedProperty',
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ReadCachedPropertyRequest.SerializeToString,
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.CachedPropertyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadAuthoritativeProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hase.runtime.remote.v1.RuntimeHostRemoteApi/ReadAuthoritativeProperty',
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ReadAuthoritativePropertyRequest.SerializeToString,
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.PropertyOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hase.runtime.remote.v1.RuntimeHostRemoteApi/WriteProperty',
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.WritePropertyRequest.SerializeToString,
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.PropertyOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hase.runtime.remote.v1.RuntimeHostRemoteApi/ExecuteCommand',
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ExecuteCommandRequest.SerializeToString,
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.CommandOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hase.runtime.remote.v1.RuntimeHostRemoteApi/Observe',
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveRequest.SerializeToString,
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObserveDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hase.runtime.remote.v1.RuntimeHostRemoteApi/ObserveDiagnostics',
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ObserveDiagnosticsRequest.SerializeToString,
            hase_dot___generated_dot_runtime__host__remote__api__v1__pb2.ProjectedDiagnosticObservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
